### ISSUE TITLE
Make features depend on config.

### ISSUE THREAD

**Issue by VictosVertex** [potassco/mkdoclingo#17]
Currently all features (dependency graph, source, glossary) are on at all times. This should be opt-in via the configuration passed in the file.

This should show the source:
```
::: encodings/sample.lp
    handler: asp
    options:
        source: True
```

This should should not:
```
::: encodings/sample.lp
    handler: asp
```
